version: '3'
services:
  judger-server:
    image: hzcool/ubuntu-judger:v2
    restart: always
    container_name: judge-server
    environment:
      - ACCESS_TOKEN=123456
      - ADDR=0.0.0.0:7777
      - TEST_CASE_DIR=/test_case
    volumes:
      - /home/hzcool/test_case:/test_case
    privileged: true
    ports:
      - "7777:7777"
